function createfigure(Y1, Y2)
%CREATEFIGURE(Y1, Y2)
%  Y1:  vector of y data
%  Y2:  vector of y data

%  Auto-generated by MATLAB on 16-May-2016 12:19:54

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1,'YMinorTick','on','XMinorTick','on','XScale','log','FontSize',16,...
    'FontName','Cambria');
%% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[-10 1010]);
%% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[0.0036 2]);
box(axes1,'on');
grid(axes1,'on');
hold(axes1,'on');

% Create ylabel
ylabel(['Solute Concentration';' [gr/M3],[ppm]      ']);

% Create xlabel
xlabel('Channel Length [meters]');

% Create title
title(['Fig. (5) Solute Transport is Simulated Through Numerical and Exact Solution Schems';' Showing How the Concentration Changes Along the Channel                          '],...
    'FontSize',16,...
    'FontName','Cambria');

% Create semilogx
semilogx(Y1,'DisplayName',['Analytucal',sprintf('\n'),'Results'],...
    'MarkerFaceColor',[1 0.949019610881805 0.866666674613953],...
    'MarkerSize',0.5,...
    'Marker','o',...
    'LineWidth',2,...
    'LineStyle','-.');

% Create semilogx
semilogx(Y2,'ZDataSource','','DisplayName',['Numerical',sprintf('\n'),' Results'],...
    'MarkerEdgeColor','none',...
    'LineWidth',2,...
    'LineStyle','--',...
    'Color',[0.85 0.325 0.098]);

% Create legend
legend1 = legend(axes1,'show');
set(legend1,'FontSize',14.4);

